version: '3'
services:

  job-storage:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: job-storage
    ports:
      - "2000:2000"
    image: zoldak/job-storage:1.0
    networks:
      - jobs-backend
    links:
      - postgres-jobs
      - rsyslog

  postgres-jobs:
    image: postgres
    container_name: postgres-jobs
    ports:
      - 5442:5432
    environment:
      - POSTGRES_PASSWORD=aweakpassword
      - POSTGRES_USER=postgres
    networks:
      - jobs-backend
    volumes:
      - './db:/var/lib/postgresql/data'


  rsyslog:
    image: vimagick/rsyslog
    networks:
      - jobs-backend
    volumes:
      - './log:/var/log'
    restart: always

networks:
  jobs-backend: null
